-- Insert Values (Vendedores Fonte Novos)
INSERT INTO TABELA_DE_VENDEDORES_FONTE (MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS, BAIRRO) VALUES ('00234', 'Rafael Garrido Silva', 0.12, TO_DATE('2013-02-07','YYYY-MM-DD'), 0, 'Moema');
INSERT INTO TABELA_DE_VENDEDORES_FONTE (MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS, BAIRRO) VALUES ('00233', 'Thais Balduco', 0.08,  TO_DATE('2013-12-27','YYYY-MM-DD'), 0, 'Aclimação');
INSERT INTO TABELA_DE_VENDEDORES_FONTE (MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS, BAIRRO) VALUES ('00232', 'Renato Almeida Junior', 0.10,  TO_DATE('2014-01-18','YYYY-MM-DD'), 0, 'Copacabana');
INSERT INTO TABELA_DE_VENDEDORES_FONTE (MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS, BAIRRO) VALUES ('00231', 'Fernanda Alves Cabral', 0.06,  TO_DATE('2010-05-11','YYYY-MM-DD'), 0, 'Santo Andre');
-- Insert Values (Vendedores Fonte Existentes)
INSERT INTO TABELA_DE_VENDEDORES_FONTE (MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS, BAIRRO) VALUES ('00235', 'Marcio Almeida Silva', 0.08, TO_DATE('2014-08-15','YYYY-MM-DD'), 0, 'Tijuca');
INSERT INTO TABELA_DE_VENDEDORES_FONTE (MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS, BAIRRO) VALUES ('00236', 'Claudia Morais', 0.08,  TO_DATE('2013-09-17','YYYY-MM-DD'), 1, 'Jardins');
INSERT INTO TABELA_DE_VENDEDORES_FONTE (MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS, BAIRRO) VALUES ('00237', 'Roberta Martins', 0.11,  TO_DATE('2017-03-18','YYYY-MM-DD'), 1, 'Copacabana');
INSERT INTO TABELA_DE_VENDEDORES_FONTE (MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS, BAIRRO) VALUES ('00238', 'Pericles Alves', 0.11,  TO_DATE('2016-08-21','YYYY-MM-DD'), 0, 'Santo Amaro');