DROP TABLE TABELA_DE_VENDEDORES_FONTE

-- Create Tabela Vendedores Fonte
CREATE TABLE TABELA_DE_VENDEDORES_FONTE
     (
     MATRICULA NVARCHAR2(5) NOT NULL,
     NOME NVARCHAR2(100),
     PERCENTUAL_COMISSAO FLOAT,
     DATA_ADMISSAO DATE,
     DE_FERIAS NUMBER(1,0),
     BAIRRO NVARCHAR2(50)
     );
